### ISSUE TITLE
YOURAPIKEYHERE

### ISSUE THREAD

**Issue by ernany** [westparkcom/Lua-Bing-TTS#1]
How to get "YOURAPIKEYHERE"?

I'm trying for the azure portal >> Text Translator API >> RESOURCE MANAGEMENT >> Keys >> KEY 1

**Comment by jpattWPC** [comment]
You need to use the "Cognitive Services API (Preview)" for this to work. In the marketplace it's under Intelligence + analytics.
![microsoft azure - cognitive services apis](https://cloud.githubusercontent.com/assets/16338864/24200789/2f0a4de6-0edc-11e7-99c3-d2b07b61bf77.png)

Then once you've added that to azure you will need to get the API key:
![manage keys - microsoft azure](https://cloud.githubusercontent.com/assets/16338864/24200823/460d939a-0edc-11e7-9b44-b7c8acb77af6.png)

**Comment by ernany** [comment]
It was done that way and I still get 403

**Comment by ernany** [comment]
Thanks I was able to make it work missing API type
